baseURL = 'https://dialectapp.org'
languageCode = 'en'
title = 'Dialect'

disableKinds = ['taxonomy', 'term']

[menus]
[[menus.main]]
    name = 'About'
    url = '/#about'
    weight = 10
[[menus.main]]
    name = 'Hosted Services'
    url = '/#hosted-services'
    weight = 20
[[menus.main]]
    name = 'Donate'
    url = '/#donate'
    weight = 30
[[menus.main]]
    name = 'Code'
    url = 'https://github.com/dialect-app'

[[menus.footer]]
    name = 'Website Stats'
    url = 'https://analytics.odka.org/dialectapp.org'
    weight = 10
[[menus.footer]]
    name = 'Services Status'
    url = 'https://status.dialectapp.org/'
    weight = 20

[markup.goldmark.renderer]
unsafe= true
